### ISSUE TITLE
mongoose deprecation warning

### ISSUE THREAD

**Issue by holaymolay** [codeclubsocial/codeclub_website_dev#31]
Received this upon server bootup:

(node:73036) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client

**Comment by craig429** [comment]
Indeed, there is also this:
`Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.`

We are certain to get various `Deprecated` feature warnings as things evolve. Since the first looks straightforward (I've regretted saying THAT before) and second involves auth I will assign this to myself.

**Comment by holaymolay** [comment]
Yes, that would be issue #30. I'm unsure if they're related, so I created them as separate issues. This one has to do with the Mongoose module while the other one refers to MongoDB only

**Comment by craig429** [comment]
This warning will go away when we merge validation_branch. Closing.
